### PR TITLE
Fix issue with missing emails

### LINKED ISSUE #950: [Airbrake] [Production] undefined method `number' for nil
**Airbrake error:** [#3352](https://herokuapp32817511herokucom.airbrake.io/projects/110137/groups/3839266575704363352)
**Airbrake project:** swapmyvote

**Error type:** `NoMethodError`
**Error message:** `` undefined method `number' for nil ``
**Where:** `mobile_phone#verify_create`
**Occurred at:** Jul 03, 2024 04:17:19 UTC
**First seen at:** Jul 03, 2024 04:17:19 UTC
**Occurrences:** 0 (0 since last deploy on `<no information>`)
**Severity:** `error`

**URL:** [https://www.swapmyvote.uk/mobile_phone/verify_create](https://www.swapmyvote.uk/mobile_phone/verify_create)
**File:** `/PROJECT_ROOT/app/controllers/mobile_phone_controller.rb`

**Backtrace:**
```
/PROJECT_ROOT/app/controllers/mobile_phone_controller.rb:62:in api_get_otp
/PROJECT_ROOT/app/controllers/mobile_phone_controller.rb:10:in verify_create
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal/basic_implicit_render.rb:6:in send_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/abstract_controller/base.rb:228:in process_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal/rendering.rb:30:in process_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/abstract_controller/callbacks.rb:42:in block in process_action
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in block in run_callbacks
/GEM_ROOT/gems/actiontext-6.1.7.8/lib/action_text/rendering.rb:20:in with_renderer
/GEM_ROOT/gems/actiontext-6.1.7.8/lib/action_text/engine.rb:59:in block (4 levels) in <class:Engine>
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in instance_exec
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in block in run_callbacks
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in run_callbacks
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/abstract_controller/callbacks.rb:41:in process_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal/rescue.rb:22:in process_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal/instrumentation.rb:34:in block in process_action
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in block in instrument
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in instrument
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in instrument
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal/instrumentation.rb:33:in process_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal/params_wrapper.rb:249:in process_action
/GEM_ROOT/gems/activerecord-6.1.7.8/lib/active_record/railties/controller_runtime.rb:27:in process_action
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/abstract_controller/base.rb:165:in process
/GEM_ROOT/gems/actionview-6.1.7.8/lib/action_view/rendering.rb:39:in process
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal.rb:190:in dispatch
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_controller/metal.rb:254:in dispatch
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:50:in dispatch
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:33:in serve
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:50:in block in serve
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in each
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/journey/router.rb:32:in serve
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/routing/route_set.rb:842:in call
/GEM_ROOT/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:202:in call!
/GEM_ROOT/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in call
/GEM_ROOT/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:202:in call!
/GEM_ROOT/gems/omniauth-2.1.2/lib/omniauth/strategy.rb:169:in call
/GEM_ROOT/gems/omniauth-2.1.2/lib/omniauth/builder.rb:44:in call
/GEM_ROOT/gems/warden-1.2.9/lib/warden/manager.rb:36:in block in call
/GEM_ROOT/gems/warden-1.2.9/lib/warden/manager.rb:34:in catch
/GEM_ROOT/gems/warden-1.2.9/lib/warden/manager.rb:34:in call
/GEM_ROOT/gems/rack-2.2.9/lib/rack/tempfile_reaper.rb:15:in call
/GEM_ROOT/gems/rack-2.2.9/lib/rack/etag.rb:27:in call
/GEM_ROOT/gems/rack-2.2.9/lib/rack/conditional_get.rb:27:in call
/GEM_ROOT/gems/rack-2.2.9/lib/rack/head.rb:12:in call
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/http/permissions_policy.rb:22:in call
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/http/content_security_policy.rb:19:in call
/GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:266:in context
/GEM_ROOT/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:260:in call
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/cookies.rb:697:in call
/GEM_ROOT/gems/actionpack-6.1.7.8/lib/action_dispatch/middleware/callbacks.rb:27:in block in call
/GEM_ROOT/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:98:in run_callbacks
...
```
Visit [Airbrake error](https://herokuapp32817511herokucom.airbrake.io/projects/110137/groups/3839266575704363352?tab=notice-detail) to view the full backtrace.

### LINKED ISSUE #952: System error reports this morning
Coming in in email and Twitter 

"Hi There,
When I click 'offer to swap' I get an error. I've tried with a few people now? Any advice?
THanks
Will"
image

### LINKED ISSUE #953: Don't allow email address as user name
People can give away their privacy eg in a swap offer email

### PR DESCRIPTION
**Pull request by stevebaxter**
If the user doesn't have a verified mobile number and they try to swap then we send the validation code to them. Unfortunately if they don't have a number at all then we will crash as there's no mobile number to send the code to!

To fix this, if the user has no mobile number at all we redirect to the user edit page for them to provide it.

We also add a check that the email and name aren't the same, this fixes #953.

Finally we tidy up some more UI:

1. Adding required stars to things that are required
2. Centre buttons so we're consistent
3. Remove "!" from UI text

Closes #953
Closes #952
Closes #950

### CODE REVIEW

File: app/controllers/user/swaps_controller.rb [hunk 1]
```diff
@@ -57,6 +58,13 @@ def destroy
 
   private
 
+  def assert_mobile_phone_present
+    return unless @user.mobile_phone.blank?
+
+    flash[:errors] = ["Please enter your mobile phone number before you swap"]
+    redirect_to edit_user_path
```
Comment (stevebaxter) [inline app/controllers/user/swaps_controller.rb:65]: This fixes the crash

File: app/models/user.rb [hunk 2]
```diff
@@ -33,9 +33,14 @@ class User < ApplicationRecord
   # Additional validation for emails, :validatable has already added basic validation
   validate :email_uniqueness, on: :create
 
+  # Required fields
   validates :name, presence: true
+  validates :email, presence: true
```
Comment (stevebaxter) [inline app/models/user.rb:38]: This is required by devise, but the user can delete it again. I don't think we should allow that.

File: app/models/user.rb [hunk 3]
```diff
@@ -33,9 +33,14 @@ class User < ApplicationRecord
...
   validates :consent_to_data_processing, acceptance: true
 
+  # Name cannot be the same as email
+  validate :check_email_and_name
```
Comment (stevebaxter) [inline app/models/user.rb:42]: #953

File: app/views/mobile_phone/verify_token.html.haml [hunk 4]
```diff
@@ -3,14 +3,15 @@
...
-          %h1.h4.mb-0 Verification successful!
+          %h1.h4.mb-0 Verification successful
 
         .card-body
           %p
             Thank you for verifying your mobile phone number.
 
-          = link_to user_path do
-            = button_tag "Continue", class: 'btn btn-primary'
+          .d-flex.justify-content-center
```
Comment (stevebaxter) [inline app/views/mobile_phone/verify_token.html.haml:12]: Centre the button

File: spec/controllers/user/swaps_controller_spec.rb [hunk 5]
```diff
@@ -5,7 +5,8 @@
 
   context "when user has a potential swap" do
     let(:new_user) do
-      build(:user, id: 121, email: "foo@bar.com")
+      build(:user, id: 121, email: "foo@bar.com",
+      mobile_phone: build(:mobile_phone, user_id: 122, number: "07400 123456", verified: false))
```
Comment (stevebaxter) [inline spec/controllers/user/swaps_controller_spec.rb:9]: We need proper fixtures here really but I don't have time to mess with this right now!

File: spec/controllers/user/swaps_controller_spec.rb [hunk 6]
```diff
@@ -329,8 +327,57 @@
             email: "")
     end
 
-    let(:mobile_phone) do
-      build(:mobile_phone, user_id: 122, number: "07400 123456", verified: true)
+    let(:swap_user) do
```
Comment (stevebaxter) [inline spec/controllers/user/swaps_controller_spec.rb:330]: GH has chosen a weird diff here - the "when users don't have an email" test is basically the same, the "when users don't have an mobile number" test is new.

File: app/controllers/user/swaps_controller.rb [hunk 7]
```diff
@@ -66,14 +74,14 @@ def assert_mobile_phone_verified
   def assert_has_email
     return unless @user.email.blank?
 
-    flash[:errors] = ["Please enter your email address before you swap!"]
+    flash[:errors] = ["Please enter your email address before you swap"]
```
Comment (aspiers) [inline app/controllers/user/swaps_controller.rb:77]: These should end in `.` too, no? But not a merge-blocker.

File: app/models/user.rb [hunk 8]
```diff
@@ -391,6 +396,10 @@ def email_uniqueness
     email_uniqueness_errors(existing_user)
   end
 
+  def check_email_and_name
+    errors.add(:name, "can't be the same as email") if email == name
```
Comment (aspiers) [inline app/models/user.rb:400]: This isn't strong enough a check; I saw a case where the email and name only differed by capitalisation.  We need to prevent `@` in the name.

**Review by aspiers — APPROVED** [review]

File: app/controllers/user/swaps_controller.rb (hunk 7 above)
Comment (stevebaxter) [reply app/controllers/user/swaps_controller.rb:77]: No it probably shouldn't. I would generally end with a "." if it's multiple sentences but not otherwise.
