### PR TITLE
Change information message when token is wrong

### LINKED ISSUE #131: Improve phone verification UX
We need to improve the text and placement of error messages when wrong or expired verification tokens are entered and a new one gets sent.  Currently the UX is a bit confusing.

### PR DESCRIPTION
**Pull request by egglestn**
New information message, as suggested in https://github.com/swapmyvote/swapmyvote/issues/131

Closes #131.

### CODE REVIEW

**Comment by aspiers** [comment]
@cla-bot check

**Comment by egglestn** [comment]
CLosing then re-opening to poke travis

**Comment by egglestn** [comment]
Travis have unflagged my account, trying close and reopen again

**Comment by egglestn** [comment]
@aspiers where is the best place to go to do the mobile verification? Does the travis build get posted to staging?

**Comment by aspiers** [comment]
No I do it manually. Deployed just an hour ago. But you can also test it
locally by setting MESSAGEBIRD_API_KEY environment variable, which I can
send you.

**Comment by egglestn** [comment]
Tested on localhost, here's a screenshot: 
image

**Comment by egglestn** [comment]
Possibly change the styling of the error message under the verify box? It's not completely obvious that it's an error message

**Comment by tdg** [comment]
Agreed. Perhaps use a red text box, or simply add a ⚠️ emoji to both ends of the copy?

File: app/controllers/mobile_phone_controller.rb [hunk 1]
```diff
@@ -28,7 +28,8 @@ def verify_token
                                                   params[:token])
 
     if errors
-      handle_errors(errors, "Failed to verify code to #{number}")
+
+      handle_errors([], "**Verifying phone number**")
```
Comment (aspiers) [inline app/controllers/mobile_phone_controller.rb]: Ah sorry, I think there's a misunderstanding here.  When [@tdg wrote `**Verifying phone number**`](https://github.com/swapmyvote/swapmyvote/issues/131#issuecomment-557829090) I think he was referring to the *existing* `<h1>` header.  We don't want this text to appear again above it.

File: app/views/mobile_phone/verify_create.html.haml [hunk 2]
```diff
@@ -26,6 +26,11 @@
             oninput: "setCustomValidity('')"
         = button_tag "Verify"
 
+      - if flash[:errors]
```
Comment (aspiers) [inline app/views/mobile_phone/verify_create.html.haml]: I think we need to check what the error is here.  We can't assume that it's always a "wrong token" error.  It might be "token expired", or something else.

File: app/views/mobile_phone/verify_create.html.haml [hunk 3]
```diff
@@ -26,6 +26,11 @@
...
+        %p.field-error
+          Oh dear, that doesn't seem to be right. We will send you a new 6
```
Comment (aspiers) [inline app/views/mobile_phone/verify_create.html.haml]: This should appear immediately below the `<h1>`, in red, and in lieu of the "A verfication code was sent to ..." sentence.

**Comment by egglestn** [comment]
> This needs a few tweaks as explained - sorry, the issue description was probably not very clear. Might be quicker to have a short chat on the phone so we're on the same page about how to fix these mobile verification things?

See slack to arrange a call...?

**Comment by egglestn** [comment]
How it looks now:     
image

**Comment by aspiers** [comment]
I'm in the middle of working on this.
